# nixpacks.toml para projeto-clima (Angular)
[phases.setup]
cmds = ["npm ci"]

[phases.build]
cmds = ["npm run build -- --configuration=production"]

[phases.install]
cmds = ["npm install -g serve"]

[start]
cmd = "serve -s dist/projeto-clima --listen tcp://0.0.0.0:$PORT"
